{{ if .Values.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: mc-join-config
 namespace: kasten-io
data:
 cluster-name: {{ .Values.name }}
 cluster-ingress: {{ .Values.secondaryUrl }}
 primary-ingress: {{ .Values.primaryUrl }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mc-join
  namespace: kasten-io
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.clusterSecretStore }}
  target:
    name: mc-join
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: {{ .Values.remoteKey }}
{{- end }}