auth:
  tokenAuth:
    enabled: true
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  create: true
  host: kasten.mcourcy-primary.customers.kastenevents.com
  tls:
    enabled: true
    secretName: kasten-gateway-tls-secret
  urlPath: k10
