global:
  domain: argocd.mcourcy-primary.customers.kastenevents.com

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    extraTls:
      - hosts:
        - argocd.mcourcy-primary.customers.kastenevents.com
        # Based on the ingress controller used secret might be optional
        secretName: argocd-tls